version: '3.8'

services:
  payload-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petmate_payload_app
    ports:
      - '3000:3000'
    volumes:
      # Gắn thư mục chứa file SQLite cũ của bạn vào Docker
      - ./docker_db:/app/data
      # (Tùy chọn) Gắn thư mục media nếu bạn muốn lưu ảnh ở máy host không bị mất
      - ./media:/app/media
    env_file:
      - .env
    restart: always
